// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/koo-arch/adjusta-backend/ent/calendar"
	"github.com/koo-arch/adjusta-backend/ent/googlecalendarinfo"
	"github.com/koo-arch/adjusta-backend/ent/predicate"
)

// GoogleCalendarInfoQuery is the builder for querying GoogleCalendarInfo entities.
type GoogleCalendarInfoQuery struct {
	config
	ctx           *QueryContext
	order         []googlecalendarinfo.OrderOption
	inters        []Interceptor
	predicates    []predicate.GoogleCalendarInfo
	withCalendars *CalendarQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GoogleCalendarInfoQuery builder.
func (gciq *GoogleCalendarInfoQuery) Where(ps ...predicate.GoogleCalendarInfo) *GoogleCalendarInfoQuery {
	gciq.predicates = append(gciq.predicates, ps...)
	return gciq
}

// Limit the number of records to be returned by this query.
func (gciq *GoogleCalendarInfoQuery) Limit(limit int) *GoogleCalendarInfoQuery {
	gciq.ctx.Limit = &limit
	return gciq
}

// Offset to start from.
func (gciq *GoogleCalendarInfoQuery) Offset(offset int) *GoogleCalendarInfoQuery {
	gciq.ctx.Offset = &offset
	return gciq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (gciq *GoogleCalendarInfoQuery) Unique(unique bool) *GoogleCalendarInfoQuery {
	gciq.ctx.Unique = &unique
	return gciq
}

// Order specifies how the records should be ordered.
func (gciq *GoogleCalendarInfoQuery) Order(o ...googlecalendarinfo.OrderOption) *GoogleCalendarInfoQuery {
	gciq.order = append(gciq.order, o...)
	return gciq
}

// QueryCalendars chains the current query on the "calendars" edge.
func (gciq *GoogleCalendarInfoQuery) QueryCalendars() *CalendarQuery {
	query := (&CalendarClient{config: gciq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gciq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gciq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(googlecalendarinfo.Table, googlecalendarinfo.FieldID, selector),
			sqlgraph.To(calendar.Table, calendar.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, googlecalendarinfo.CalendarsTable, googlecalendarinfo.CalendarsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(gciq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GoogleCalendarInfo entity from the query.
// Returns a *NotFoundError when no GoogleCalendarInfo was found.
func (gciq *GoogleCalendarInfoQuery) First(ctx context.Context) (*GoogleCalendarInfo, error) {
	nodes, err := gciq.Limit(1).All(setContextOp(ctx, gciq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{googlecalendarinfo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (gciq *GoogleCalendarInfoQuery) FirstX(ctx context.Context) *GoogleCalendarInfo {
	node, err := gciq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GoogleCalendarInfo ID from the query.
// Returns a *NotFoundError when no GoogleCalendarInfo ID was found.
func (gciq *GoogleCalendarInfoQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = gciq.Limit(1).IDs(setContextOp(ctx, gciq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{googlecalendarinfo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (gciq *GoogleCalendarInfoQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := gciq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GoogleCalendarInfo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GoogleCalendarInfo entity is found.
// Returns a *NotFoundError when no GoogleCalendarInfo entities are found.
func (gciq *GoogleCalendarInfoQuery) Only(ctx context.Context) (*GoogleCalendarInfo, error) {
	nodes, err := gciq.Limit(2).All(setContextOp(ctx, gciq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{googlecalendarinfo.Label}
	default:
		return nil, &NotSingularError{googlecalendarinfo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (gciq *GoogleCalendarInfoQuery) OnlyX(ctx context.Context) *GoogleCalendarInfo {
	node, err := gciq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GoogleCalendarInfo ID in the query.
// Returns a *NotSingularError when more than one GoogleCalendarInfo ID is found.
// Returns a *NotFoundError when no entities are found.
func (gciq *GoogleCalendarInfoQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = gciq.Limit(2).IDs(setContextOp(ctx, gciq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{googlecalendarinfo.Label}
	default:
		err = &NotSingularError{googlecalendarinfo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (gciq *GoogleCalendarInfoQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := gciq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GoogleCalendarInfos.
func (gciq *GoogleCalendarInfoQuery) All(ctx context.Context) ([]*GoogleCalendarInfo, error) {
	ctx = setContextOp(ctx, gciq.ctx, "All")
	if err := gciq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GoogleCalendarInfo, *GoogleCalendarInfoQuery]()
	return withInterceptors[[]*GoogleCalendarInfo](ctx, gciq, qr, gciq.inters)
}

// AllX is like All, but panics if an error occurs.
func (gciq *GoogleCalendarInfoQuery) AllX(ctx context.Context) []*GoogleCalendarInfo {
	nodes, err := gciq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GoogleCalendarInfo IDs.
func (gciq *GoogleCalendarInfoQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if gciq.ctx.Unique == nil && gciq.path != nil {
		gciq.Unique(true)
	}
	ctx = setContextOp(ctx, gciq.ctx, "IDs")
	if err = gciq.Select(googlecalendarinfo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (gciq *GoogleCalendarInfoQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := gciq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (gciq *GoogleCalendarInfoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, gciq.ctx, "Count")
	if err := gciq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, gciq, querierCount[*GoogleCalendarInfoQuery](), gciq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (gciq *GoogleCalendarInfoQuery) CountX(ctx context.Context) int {
	count, err := gciq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (gciq *GoogleCalendarInfoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, gciq.ctx, "Exist")
	switch _, err := gciq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (gciq *GoogleCalendarInfoQuery) ExistX(ctx context.Context) bool {
	exist, err := gciq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GoogleCalendarInfoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (gciq *GoogleCalendarInfoQuery) Clone() *GoogleCalendarInfoQuery {
	if gciq == nil {
		return nil
	}
	return &GoogleCalendarInfoQuery{
		config:        gciq.config,
		ctx:           gciq.ctx.Clone(),
		order:         append([]googlecalendarinfo.OrderOption{}, gciq.order...),
		inters:        append([]Interceptor{}, gciq.inters...),
		predicates:    append([]predicate.GoogleCalendarInfo{}, gciq.predicates...),
		withCalendars: gciq.withCalendars.Clone(),
		// clone intermediate query.
		sql:  gciq.sql.Clone(),
		path: gciq.path,
	}
}

// WithCalendars tells the query-builder to eager-load the nodes that are connected to
// the "calendars" edge. The optional arguments are used to configure the query builder of the edge.
func (gciq *GoogleCalendarInfoQuery) WithCalendars(opts ...func(*CalendarQuery)) *GoogleCalendarInfoQuery {
	query := (&CalendarClient{config: gciq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	gciq.withCalendars = query
	return gciq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		GoogleCalendarID string `json:"google_calendar_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GoogleCalendarInfo.Query().
//		GroupBy(googlecalendarinfo.FieldGoogleCalendarID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (gciq *GoogleCalendarInfoQuery) GroupBy(field string, fields ...string) *GoogleCalendarInfoGroupBy {
	gciq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GoogleCalendarInfoGroupBy{build: gciq}
	grbuild.flds = &gciq.ctx.Fields
	grbuild.label = googlecalendarinfo.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		GoogleCalendarID string `json:"google_calendar_id,omitempty"`
//	}
//
//	client.GoogleCalendarInfo.Query().
//		Select(googlecalendarinfo.FieldGoogleCalendarID).
//		Scan(ctx, &v)
func (gciq *GoogleCalendarInfoQuery) Select(fields ...string) *GoogleCalendarInfoSelect {
	gciq.ctx.Fields = append(gciq.ctx.Fields, fields...)
	sbuild := &GoogleCalendarInfoSelect{GoogleCalendarInfoQuery: gciq}
	sbuild.label = googlecalendarinfo.Label
	sbuild.flds, sbuild.scan = &gciq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GoogleCalendarInfoSelect configured with the given aggregations.
func (gciq *GoogleCalendarInfoQuery) Aggregate(fns ...AggregateFunc) *GoogleCalendarInfoSelect {
	return gciq.Select().Aggregate(fns...)
}

func (gciq *GoogleCalendarInfoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range gciq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, gciq); err != nil {
				return err
			}
		}
	}
	for _, f := range gciq.ctx.Fields {
		if !googlecalendarinfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if gciq.path != nil {
		prev, err := gciq.path(ctx)
		if err != nil {
			return err
		}
		gciq.sql = prev
	}
	return nil
}

func (gciq *GoogleCalendarInfoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GoogleCalendarInfo, error) {
	var (
		nodes       = []*GoogleCalendarInfo{}
		_spec       = gciq.querySpec()
		loadedTypes = [1]bool{
			gciq.withCalendars != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GoogleCalendarInfo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GoogleCalendarInfo{config: gciq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, gciq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := gciq.withCalendars; query != nil {
		if err := gciq.loadCalendars(ctx, query, nodes,
			func(n *GoogleCalendarInfo) { n.Edges.Calendars = []*Calendar{} },
			func(n *GoogleCalendarInfo, e *Calendar) { n.Edges.Calendars = append(n.Edges.Calendars, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (gciq *GoogleCalendarInfoQuery) loadCalendars(ctx context.Context, query *CalendarQuery, nodes []*GoogleCalendarInfo, init func(*GoogleCalendarInfo), assign func(*GoogleCalendarInfo, *Calendar)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*GoogleCalendarInfo)
	nids := make(map[uuid.UUID]map[*GoogleCalendarInfo]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(googlecalendarinfo.CalendarsTable)
		s.Join(joinT).On(s.C(calendar.FieldID), joinT.C(googlecalendarinfo.CalendarsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(googlecalendarinfo.CalendarsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(googlecalendarinfo.CalendarsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*GoogleCalendarInfo]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Calendar](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "calendars" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (gciq *GoogleCalendarInfoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := gciq.querySpec()
	_spec.Node.Columns = gciq.ctx.Fields
	if len(gciq.ctx.Fields) > 0 {
		_spec.Unique = gciq.ctx.Unique != nil && *gciq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, gciq.driver, _spec)
}

func (gciq *GoogleCalendarInfoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(googlecalendarinfo.Table, googlecalendarinfo.Columns, sqlgraph.NewFieldSpec(googlecalendarinfo.FieldID, field.TypeUUID))
	_spec.From = gciq.sql
	if unique := gciq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if gciq.path != nil {
		_spec.Unique = true
	}
	if fields := gciq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, googlecalendarinfo.FieldID)
		for i := range fields {
			if fields[i] != googlecalendarinfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := gciq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := gciq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := gciq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := gciq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (gciq *GoogleCalendarInfoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(gciq.driver.Dialect())
	t1 := builder.Table(googlecalendarinfo.Table)
	columns := gciq.ctx.Fields
	if len(columns) == 0 {
		columns = googlecalendarinfo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if gciq.sql != nil {
		selector = gciq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if gciq.ctx.Unique != nil && *gciq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range gciq.predicates {
		p(selector)
	}
	for _, p := range gciq.order {
		p(selector)
	}
	if offset := gciq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := gciq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GoogleCalendarInfoGroupBy is the group-by builder for GoogleCalendarInfo entities.
type GoogleCalendarInfoGroupBy struct {
	selector
	build *GoogleCalendarInfoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (gcigb *GoogleCalendarInfoGroupBy) Aggregate(fns ...AggregateFunc) *GoogleCalendarInfoGroupBy {
	gcigb.fns = append(gcigb.fns, fns...)
	return gcigb
}

// Scan applies the selector query and scans the result into the given value.
func (gcigb *GoogleCalendarInfoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, gcigb.build.ctx, "GroupBy")
	if err := gcigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GoogleCalendarInfoQuery, *GoogleCalendarInfoGroupBy](ctx, gcigb.build, gcigb, gcigb.build.inters, v)
}

func (gcigb *GoogleCalendarInfoGroupBy) sqlScan(ctx context.Context, root *GoogleCalendarInfoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(gcigb.fns))
	for _, fn := range gcigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*gcigb.flds)+len(gcigb.fns))
		for _, f := range *gcigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*gcigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gcigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GoogleCalendarInfoSelect is the builder for selecting fields of GoogleCalendarInfo entities.
type GoogleCalendarInfoSelect struct {
	*GoogleCalendarInfoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (gcis *GoogleCalendarInfoSelect) Aggregate(fns ...AggregateFunc) *GoogleCalendarInfoSelect {
	gcis.fns = append(gcis.fns, fns...)
	return gcis
}

// Scan applies the selector query and scans the result into the given value.
func (gcis *GoogleCalendarInfoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, gcis.ctx, "Select")
	if err := gcis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GoogleCalendarInfoQuery, *GoogleCalendarInfoSelect](ctx, gcis.GoogleCalendarInfoQuery, gcis, gcis.inters, v)
}

func (gcis *GoogleCalendarInfoSelect) sqlScan(ctx context.Context, root *GoogleCalendarInfoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(gcis.fns))
	for _, fn := range gcis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*gcis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gcis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
