// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Calendar is the predicate function for calendar builders.
type Calendar func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// JWTKey is the predicate function for jwtkey builders.
type JWTKey func(*sql.Selector)

// ProposedDate is the predicate function for proposeddate builders.
type ProposedDate func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
